branches:
  only:
    - dooodle

sudo: required

services:
  - docker
notifications:
  slack: dooodle:hots3bBY7zx3Dff7425iO67W

script:
  - bash get-latest-mondial-nt
  # - cat jena-fuseki/mondial.nt
  - sed -i "s/ENV ADMIN_PASSWORD=.*/ENV ADMIN_PASSWORD=$ADMIN_PASSWORD/" "jena-fuseki/Dockerfile"
  - docker build -t dooodle/jena jena
  - docker build -t dooodle/jena-fuseki jena-fuseki
  - bash docker_push
  - bash install-kubectl
  - kubectl get pods | grep fuseki
  - kubectl patch deployment fuseki-deployment -p   "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl get pods | grep fuseki
  

