apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuseki-deployment
  labels:
    app: fuseki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuseki
  template:
    metadata:
      labels:
        app: fuseki
    spec:
      containers:
      - name: fuseki
        image: dooodle/jena-fuseki:latest
        imagePullPolicy: Always
        env: 
        # - name: SHRUG
        #   value: ""
        ports:
        - containerPort: 3030
